
# NumPy


In [1]:
# Import the numpy package under the name np
import numpy as np



### Create a numpy array of size 10, filled with zeros.

In [2]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



### Create a numpy array with values ranging from 10 to 49

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


### Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
# your code goes here
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
np.ones([3,2],dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [9]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

array([1, 1, 1, 1])


### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [10]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
# your code goes here


In [12]:
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [13]:
# your code goes here


In [14]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])


### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [17]:
np.random.randint(10, size=4)


array([5, 9, 6, 4])

In [18]:
np.random.randint(10, size=3)

array([1, 2, 8])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [19]:
np.random.random((3,3,3))


array([[[0.68690861, 0.31355176, 0.66027783],
        [0.54562146, 0.82221326, 0.41709691],
        [0.3300993 , 0.28589499, 0.64487334]],

       [[0.96860562, 0.51986069, 0.92159182],
        [0.77545912, 0.72718814, 0.65844377],
        [0.44466549, 0.55824688, 0.17091618]],

       [[0.43181707, 0.95395579, 0.50271745],
        [0.53124616, 0.82560263, 0.1626351 ],
        [0.18356461, 0.05510306, 0.57059013]]])

In [20]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[-0.56534097,  0.3479215 , -0.42403974],
        [-0.63606391, -1.07528409,  2.58803691],
        [-0.38325064,  1.18142109, -0.49773075]],

       [[-1.34392329,  0.66614679, -0.08532073],
        [-0.93013431, -1.67076508,  0.41831984],
        [-0.21995281, -0.20021827, -0.17125597]],

       [[ 0.82934795, -0.65555715,  1.36505431],
        [-0.5095201 ,  0.81076692,  0.0266725 ],
        [ 0.98959947, -1.80834916,  0.31782968]]])


### Given the X python list convert it to an Y numpy array

In [21]:
x=[3,5,7]
print(x,type(x))

y= np.array(x)
print(y,type(y))


[3, 5, 7] <class 'list'>
[3 5 7] <class 'numpy.ndarray'>


In [22]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>




### Given the X numpy array, make a copy and store it on Y.

In [23]:
x= np.array([3,4,6,7])
y= np.copy(x)
print(y)

[3 4 6 7]


In [24]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 104494888
[5 2 3] 104647360



### Create a numpy array with numbers from 1 to 10

In [25]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a numpy array with the odd numbers between 1 to 10

In [27]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [28]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [29]:
# your code goes here
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [30]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [31]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


### Show the memory size of the given Z numpy matrix

In [33]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes




## Array indexation


### Given the X numpy array, show it's first element

In [34]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'



### Given the X numpy array, show it's last element

In [35]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'


### Given the X numpy array, show it's first three elements

In [36]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')



### Given the X numpy array, show all middle elements

In [37]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')



### Given the X numpy array, show the elements in reverse position

In [38]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')



### Given the X numpy array, show the elements in an odd position

In [39]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')


### Given the X numpy matrix, show the first row elements

In [40]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])


### Given the X numpy matrix, show the last row elements

In [41]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])



### Given the X numpy matrix, show the first element on first row

In [42]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1



### Given the X numpy matrix, show the last element on last row

In [43]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16



### Given the X numpy matrix, show the middle row elements

In [44]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])


### Given the X numpy matrix, show the first two elements on the first two rows

In [45]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])



### Given the X numpy matrix, show the last two elements on the last two rows

In [46]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])


## Array manipulation


### Convert the given integer numpy array to float

In [47]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])



### Reverse the given numpy array (first element becomes last)

In [48]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]


### Order (sort) the given numpy array

In [49]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]



### Given the X numpy array, set the fifth element equal to 1

In [50]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])



### Given the X numpy array, change the 50 with a 40

In [51]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])


### Given the X numpy matrix, change the last row with all 1

In [52]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])



### Given the X numpy matrix, change the last item on the last row with a 0

In [53]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])



### Given the X numpy matrix, add 5 to every element

In [54]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### Given the X numpy array, make a mask showing negative elements

In [55]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])



### Given the X numpy array, get the negative elements

In [56]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])



### Given the X numpy array, get numbers higher than 5

In [57]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])



### Given the X numpy array, get numbers higher than the elements mean

In [58]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])



### Given the X numpy array, get numbers equal to 2 or 10

In [59]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])



## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [60]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False


### Given the X numpy array, return True if any of its elements is zero

In [61]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True



## Summary statistics

### Given the X numpy array, show the sum of its elements

In [62]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43



### Given the X numpy array, show the mean value of its elements

In [63]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7


### Given the X numpy matrix, show the sum of its columns

In [64]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])



### Given the X numpy matrix, show the mean value of its rows

In [65]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])



### Given the X numpy array, show the max value of its elements

In [66]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10